<?php
/**
 * Implements hook_page_attachments_alter().
 */
function metatag_remove_page_attachments_alter(&$page) {
  // Remove the HTML5 mobile meta-tags.
  $meta_tags_to_remove = [
    'system_meta_content_type',
    'system_meta_generator',
    'MobileOptimized',
    'HandheldFriendly',
    'viewport',
    'cleartype'
  ];
  // Unset loop.
  foreach ($page['#attached']['html_head'] as $index => $parts) {
    if (in_array($parts[1], $meta_tags_to_remove)) {
      unset($page['#attached']['html_head'][$index]);
    }
  }
}
